rules:
  - id: err-commented-debug-statements
    message: "Commented debug statements"
    languages: [go]
    severity: ERROR
    patterns:
      - pattern-regex: //\s*(fmt\.Print|println)

  - id: err-trailing-whitespaces
    message: "Trailing whitespace"
    languages: [go]
    severity: ERROR
    patterns:
      - pattern-regex: '[ \t]+$'
