// Package version is auto-generated using version/cmd/generate.go on non-release builds.
package version

// Code generated by version/cmd/generate.go. DO NOT EDIT.

import "strings"

const Version = "v0.7.0"
const GitCommit = "2a123c"

func GetHumanVersion() string {
	version := Version
	if !strings.HasPrefix(version, "v") {
		version = "v" + Version
	}

	return Version + "-" + GitCommit
}
