// Package version is auto-generated using version/cmd/generate.go on non-release builds.
package version

// Code generated by version/cmd/generate.go. DO NOT EDIT.

import "fmt"
import "strings"

const Version = "v0.7.0"
const GitCommit = "66767d"


func GetHumanVersion() string {
	version := Version
	if !strings.HasPrefix(version, "v") {
		version = fmt.Sprintf("v%v", version)
	}

	return fmt.Sprintf("%v-%v", version, GitCommit)
}
