before:
  hooks:
    - make build
builds:
  -
    binary: s5cmd
    ldflags: -s -w -X github.com/voyvodov/s5cmd/v2/version.Version={{.Tag}} -X github.com/voyvodov/s5cmd/v2/version.GitCommit={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64le
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: 32bit
      amd64: 64bit
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

nfpms:
  -
    vendor: Peak
    homepage: https://github.com/voyvodov/s5cmd
    license: MIT
    maintainer: Peak <packaging@peak.com>
    description: |-
      Very fast S3 and local filesystem execution tool. It comes with support
      for a multitude of operations including tab completion and wildcard
      support for files, which can be very handy for your object storage
      workflow while working with large number of files.
    formats:
      - deb

release:
  draft: true
