package core

import (
	"errors"
	"fmt"
	"strings"

	"github.com/aws/aws-sdk-go/aws/awserr"
)

const sdkPanicErrCode = "SdkPanic"

// AcceptableError interface defines an error which is OK-to-have, for things like "cp -n" etc. It should not be treated as an error (regarding the exit code etc)
type AcceptableError interface {
	error
	Acceptable() bool
}

// AcceptableErrorType embeds the stdlib error interface so that we can have more receivers on it
type AcceptableErrorType struct {
	error
}

// NewAcceptableError creates a new AcceptableError
func NewAcceptableError(s string) AcceptableErrorType {
	return AcceptableErrorType{errors.New(s)}
}

// Acceptable is always true for errors of AcceptableError type
func (e AcceptableErrorType) Acceptable() bool {
	return true
}

// CleanupError converts multiline error messages generated by aws-sdk-go into a single line
func CleanupError(err error) (s string) {
	s = strings.Replace(err.Error(), "\n", " ", -1)
	s = strings.Replace(s, "\t", " ", -1)
	s = strings.Replace(s, "  ", " ", -1)
	s = strings.Replace(s, "  ", " ", -1)
	s = strings.TrimSpace(s)
	return
}

// IsAcceptableError determines if the error is an AcceptableError, and if so, returns true
func IsAcceptableError(err error) bool {
	_, ok := err.(AcceptableError)
	if ok {
		return true
	}
	return false
}

func recoverer(ch chan error, where string, failed *bool) {
	if r := recover(); r != nil {
		ch <- awserr.New(sdkPanicErrCode, fmt.Sprintf("Caught %s panic", where), fmt.Errorf("%s: %v", where, r))
		f := true
		failed = &f
	}
}
