# This file was generated by GoReleaser. DO NOT EDIT.
class S5cmd < Formula
  desc "Parallel S3 and local filesystem execution tool"
  homepage "https://github.com/peak/s5cmd"
  version "1.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peak/s5cmd/releases/download/v1.2.0/s5cmd_1.2.0_macOS-64bit.tar.gz"
    sha256 "acab3f12b76e703f62be35dfb603269618eaafcfe1d6039fc6877df88ff7d0af"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v1.2.0/s5cmd_1.2.0_Linux-64bit.tar.gz"
      sha256 "ae6f16aa76a3bbb4203fe4533d866d15555905c415e82841f1394ea55770b9dc"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/peak/s5cmd/releases/download/v1.2.0/s5cmd_1.2.0_Linux-arm64.tar.gz"
        sha256 "783db5d163c49826283e12b57112b60458055da30cac445ec62ead14edf0deeb"
      else
        url "https://github.com/peak/s5cmd/releases/download/v1.2.0/s5cmd_1.2.0_Linux-armv6.tar.gz"
        sha256 "5e371311adc5fd5310f36a68702270d58e682cc9abd1f08058a5e28345a2c6b8"
      end
    end
  end

  def install
    bin.install "s5cmd"
  end

  test do
    system "#{bin}/s5cmd version"
  end
end
