# This file was generated by GoReleaser. DO NOT EDIT.
class S5cmd < Formula
  desc "Parallel S3 and local filesystem execution tool"
  homepage "https://github.com/peak/s5cmd"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peak/s5cmd/releases/download/v1.1.0/s5cmd_1.1.0_macOS-64bit.tar.gz"
    sha256 "859da218e75b1ead1be6156f7ab0c50f67543fef4f3fc14d40f6e8c4dc36074e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v1.1.0/s5cmd_1.1.0_Linux-64bit.tar.gz"
      sha256 "85321aef1a27a455c085fdda08228e3ebe1dad2655da556d7925c5d4bab400f5"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/peak/s5cmd/releases/download/v1.1.0/s5cmd_1.1.0_Linux-arm64.tar.gz"
        sha256 "50ab647bc9434725856ae8ca679a5d893655381042a4acb1e9ddb319228c232b"
      else
        url "https://github.com/peak/s5cmd/releases/download/v1.1.0/s5cmd_1.1.0_Linux-armv6.tar.gz"
        sha256 "1aad43033c2ea6b47708d4cef028e5be73b53957503238054727bba14514fb7c"
      end
    end
  end

  def install
    bin.install "s5cmd"
  end

  test do
    system "#{bin}/s5cmd version"
  end
end
