# This file was generated by GoReleaser. DO NOT EDIT.
class S5cmd < Formula
  desc "Parallel S3 and local filesystem execution tool"
  homepage "https://github.com/peak/s5cmd"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peak/s5cmd/releases/download/v1.0.0/s5cmd_1.0.0_macOS-64bit.tar.gz"
    sha256 "12bfc856c107f469ccbc4860df544962fc99b78fd9f5499a7bb6a8ef83a2549b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/peak/s5cmd/releases/download/v1.0.0/s5cmd_1.0.0_Linux-64bit.tar.gz"
      sha256 "a56eab6493fa6613d525e7329dc15ba161cd233708f3a0b168829934731c60f2"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/peak/s5cmd/releases/download/v1.0.0/s5cmd_1.0.0_Linux-arm64.tar.gz"
        sha256 "5f5439eae3c31c9f8ecbda8406b6fad3a7dc2788e5a0c370da8dc32fd1a0c407"
      else
        url "https://github.com/peak/s5cmd/releases/download/v1.0.0/s5cmd_1.0.0_Linux-armv6.tar.gz"
        sha256 "8d73ed1ff5fa4629960faf036d6d841a93e56c0c674feabb9f39ba922dc5e96b"
      end
    end
  end

  def install
    bin.install "s5cmd"
  end

  test do
    system "#{bin}/s5cmd version"
  end
end
