on: [push, pull_request]
name: CI
jobs:
  build-windows:
    strategy:
      matrix:
        go-version:
          - 1.14
        os:
          - macos
          - ubuntu
          - windows

    name: Build (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -mod=vendor .

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: make test

  qa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check fmt
      run: make check-fmt

    - name: Check vet
      run: make vet

    - name: Staticcheck
      run: make staticcheck

    - name: Unparam
      run: make unparam
